# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-18 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.BooleanField(choices=[(True, 'Produto Ativo'), (False, 'Produto Desativado')]),
        ),
    ]
