# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-30 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Tipo_produto',
            new_name='tipo_produto_id',
        ),
    ]
