# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-18 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230518_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='status',
            field=models.BooleanField(choices=[(True, 'Cobrança Ativa'), (False, 'Cobrança Desativa')]),
        ),
    ]
