# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230518_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rede_cliente',
            name='produto',
        ),
        migrations.AddField(
            model_name='rede_cliente',
            name='Posto_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Posto'),
            preserve_default=False,
        ),
    ]
