# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-19 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230519_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rede_cliente',
            old_name='Posto_id',
            new_name='posto_id',
        ),
    ]
