# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-06-15 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230613_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posto',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='posto',
            name='id_egestor',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='type_billing',
            name='corpo_email',
            field=models.TextField(default='\nPrezado {nome_financeiro},\n\nEspero que esteja bem.\n\nVenho por meio deste email apresentar a você os detalhes da cobrança referentes à locação do nosso sistema de controle, {produto}, que está instalado no {posto}.\n\nEm anexo, você encontrará os seguintes documentos:\n\nBoleto de Faturamento - {mes_anterior}\nRecibo de Locação - {mes_anterior}\nGostaria de fornecer um breve resumo dos dados para sua apreciação:\n\nPeríodo: {mes_anterior}\n\nTotal de Vouchers Comprados: {total_vaucher}\nBanhos Moedeiro: {moedeiro_q}\nBanhos Pago: {pago_q}\nBanhos Bonificado: {bonificado_q}\nBanhos Gerencial: {gerencial_q}\nBanhos Gotas: {gotas_q}\nBanhos Gotas Integrado: {gotas_integrada_q}\n\nValor por Voucher: \nMoedeiro: R$ {moedeiro_v}\nBanhos Pago: R$ {pago_v}\nBanhos Bonificado: R$ {bonificado_v}\nBanhos Gerencial: R$ {gerencial_v}\nBanhos Gotas: R$ {gotas_v}\nBanhos Gotas Integrado: R$ {gotas_integrada_v}\n\nA seguir, apresento o cálculo que originou o valor do boleto:\n\nBanhos Moedeiro: {moedeiro_q} vouchers x R$ {moedeiro_v} = R$ {moedeiro_t}\nBanhos Pagos: {pago_q} vouchers x R$ {pago_v} = R$ {pago_t}\nBanhos Bonificados: {bonificado_q} vouchers x R$ {bonificado_q} = R$ {bonificado_t}\nBanhos Gerencial: {gerencial_q} vouchers x R$ {gerencial_v} = R$ {gerencial_t}\nBanhos Gotas: {gotas_q} vouchers x R$ {gotas_v} = R$ {gotas_t}\nBanhos Gotas Integrado: {gotas_integrada_q} vouchers x R$ {gotas_integrada_v} = R$ {gotas_integrada_t}\n{desconto}\n\n{msg_max_min}\n\nAssim, o valor total do boleto é R$ {valor_boleto}, com vencimento previsto para {vencimento_boleto}.\n\nAgradecemos antecipadamente pela atenção e solicitamos a gentileza de confirmar o recebimento deste e-mail.\n\nAtenciosamente,\n    '),
        ),
    ]
