# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-19 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230519_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rede_cliente',
            name='posto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Posto'),
        ),
    ]
