# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-19 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230519_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rede_cliente',
            name='posto_id',
        ),
        migrations.AddField(
            model_name='posto',
            name='rede_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Rede_cliente'),
        ),
    ]
