# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-20 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230519_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='fixo_variavel',
            field=models.FloatField(default=0),
        ),
    ]
