# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-25 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_billing_fixo_variavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='valor_total_bonificado',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='valor_total_gerencial',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='valor_total_integracao_gotas',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='valor_total_pago',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='valor_total_pago_gotas',
        ),
    ]
