# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-05-30 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230524_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_produto',
            name='corpo_email',
        ),
        migrations.RemoveField(
            model_name='type_billing',
            name='email_cobranca',
        ),
        migrations.AddField(
            model_name='type_billing',
            name='corpo_email',
            field=models.TextField(default='0'),
        ),
    ]
